edition = "2021"
unstable_features = true
tab_spaces = 4
hard_tabs = false
reorder_imports = true
format_code_in_doc_comments = true
wrap_comments = false
format_strings = false
imports_granularity = "Item"
group_imports = "StdExternalCrate"
where_single_line = true
trailing_comma = "Vertical"
overflow_delimited_expr = true
